[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# BTCSA domain routing - each domain serves its specific content
# Add these domains as "Domain aliases" in Netlify dashboard
[[redirects]]
  from = "/"
  to = "/cc/index.html"
  status = 200
  force = true
  host = "btcsa.cc"

[[redirects]]
  from = "/*"
  to = "/cc/:splat"
  status = 200
  force = true
  host = "btcsa.cc"

[[redirects]]
  from = "/"
  to = "/email/index.html"
  status = 200
  force = true
  host = "btcsa.email"

[[redirects]]
  from = "/*"
  to = "/email/:splat"
  status = 200
  force = true
  host = "btcsa.email"

[[redirects]]
  from = "/"
  to = "/info/index.html"
  status = 200
  force = true
  host = "btcsa.info"

[[redirects]]
  from = "/*"
  to = "/info/:splat"
  status = 200
  force = true
  host = "btcsa.info"

[[redirects]]
  from = "/"
  to = "/life/index.html"
  status = 200
  force = true
  host = "btcsa.life"

[[redirects]]
  from = "/*"
  to = "/life/:splat"
  status = 200
  force = true
  host = "btcsa.life"

[[redirects]]
  from = "/"
  to = "/me/index.html"
  status = 200
  force = true
  host = "btcsa.me"

[[redirects]]
  from = "/*"
  to = "/me/:splat"
  status = 200
  force = true
  host = "btcsa.me"

[[redirects]]
  from = "/"
  to = "/biz/index.html"
  status = 200
  force = true
  host = "btcsa.biz"

[[redirects]]
  from = "/*"
  to = "/biz/:splat"
  status = 200
  force = true
  host = "btcsa.biz"

[[redirects]]
  from = "/"
  to = "/world/index.html"
  status = 200
  force = true
  host = "btcsa.world"

[[redirects]]
  from = "/*"
  to = "/world/:splat"
  status = 200
  force = true
  host = "btcsa.world"

[[redirects]]
  from = "/"
  to = "/vip/index.html"
  status = 200
  force = true
  host = "btcsa.vip"

[[redirects]]
  from = "/*"
  to = "/vip/:splat"
  status = 200
  force = true
  host = "btcsa.vip"

[[redirects]]
  from = "/"
  to = "/services/index.html"
  status = 200
  force = true
  host = "btcsa.services"

[[redirects]]
  from = "/*"
  to = "/services/:splat"
  status = 200
  force = true
  host = "btcsa.services"

[[redirects]]
  from = "/"
  to = "/agency/index.html"
  status = 200
  force = true
  host = "btcsa.agency"

[[redirects]]
  from = "/*"
  to = "/agency/:splat"
  status = 200
  force = true
  host = "btcsa.agency"

[[redirects]]
  from = "/"
  to = "/shop/index.html"
  status = 200
  force = true
  host = "btcsa.shop"

[[redirects]]
  from = "/*"
  to = "/shop/:splat"
  status = 200
  force = true
  host = "btcsa.shop"

[[redirects]]
  from = "/"
  to = "/store/index.html"
  status = 200
  force = true
  host = "btcsa.store"

[[redirects]]
  from = "/*"
  to = "/store/:splat"
  status = 200
  force = true
  host = "btcsa.store"

[[redirects]]
  from = "/"
  to = "/online/index.html"
  status = 200
  force = true
  host = "btcsa.online"

[[redirects]]
  from = "/*"
  to = "/online/:splat"
  status = 200
  force = true
  host = "btcsa.online"

[[redirects]]
  from = "/"
  to = "/pro/index.html"
  status = 200
  force = true
  host = "btcsa.pro"

[[redirects]]
  from = "/*"
  to = "/pro/:splat"
  status = 200
  force = true
  host = "btcsa.pro"

[[redirects]]
  from = "/"
  to = "/club/index.html"
  status = 200
  force = true
  host = "btcsa.club"

[[redirects]]
  from = "/*"
  to = "/club/:splat"
  status = 200
  force = true
  host = "btcsa.club"

[[redirects]]
  from = "/"
  to = "/art/index.html"
  status = 200
  force = true
  host = "btcsa.art"

[[redirects]]
  from = "/*"
  to = "/art/:splat"
  status = 200
  force = true
  host = "btcsa.art"

[[redirects]]
  from = "/"
  to = "/xyz/index.html"
  status = 200
  force = true
  host = "btcsa.xyz"

[[redirects]]
  from = "/*"
  to = "/xyz/:splat"
  status = 200
  force = true
  host = "btcsa.xyz"

# Subfolder redirects for main domain (btcsaw.com) only
[[redirects]]
  from = "/cc"
  to = "/cc/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/email"
  to = "/email/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/info"
  to = "/info/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/life"
  to = "/life/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/me"
  to = "/me/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/biz"
  to = "/biz/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/world"
  to = "/world/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/vip"
  to = "/vip/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/services"
  to = "/services/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/agency"
  to = "/agency/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/shop"
  to = "/shop/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/store"
  to = "/store/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/online"
  to = "/online/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/pro"
  to = "/pro/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/club"
  to = "/club/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/art"
  to = "/art/index.html"
  status = 200
  host = "btcsaw.com"

[[redirects]]
  from = "/xyz"
  to = "/xyz/index.html"
  status = 200
  host = "btcsaw.com"

[build.environment]
  NODE_VERSION = "18"
