[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

# Edge function registration
[[edge_functions]]
  function = "host-router"
  path = "/*"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Domain-specific rewrites - each BTCSA domain serves its own content directly
[[redirects]]
  from = "/"
  to = "/cc/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.cc", "www.btcsa.cc"]}

[[redirects]]
  from = "/"
  to = "/email/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.email", "www.btcsa.email"]}

[[redirects]]
  from = "/"
  to = "/info/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.info", "www.btcsa.info"]}

[[redirects]]
  from = "/"
  to = "/life/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.life", "www.btcsa.life"]}

[[redirects]]
  from = "/"
  to = "/me/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.me", "www.btcsa.me"]}

[[redirects]]
  from = "/"
  to = "/biz/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.biz", "www.btcsa.biz"]}

[[redirects]]
  from = "/"
  to = "/world/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.world", "www.btcsa.world"]}

[[redirects]]
  from = "/"
  to = "/vip/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.vip", "www.btcsa.vip"]}

[[redirects]]
  from = "/"
  to = "/services/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.services", "www.btcsa.services"]}

[[redirects]]
  from = "/"
  to = "/agency/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.agency", "www.btcsa.agency"]}

[[redirects]]
  from = "/"
  to = "/shop/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.shop", "www.btcsa.shop"]}

[[redirects]]
  from = "/"
  to = "/store/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.store", "www.btcsa.store"]}

[[redirects]]
  from = "/"
  to = "/online/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.online", "www.btcsa.online"]}

[[redirects]]
  from = "/"
  to = "/pro/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.pro", "www.btcsa.pro"]}

[[redirects]]
  from = "/"
  to = "/club/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.club", "www.btcsa.club"]}

[[redirects]]
  from = "/"
  to = "/art/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.art", "www.btcsa.art"]}

[[redirects]]
  from = "/"
  to = "/xyz/index.html"
  status = 200
  force = true
  conditions = {Host = ["btcsa.xyz", "www.btcsa.xyz"]}

# Subfolder redirects for main domain (btcsaw.com) only
[[redirects]]
  from = "/cc"
  to = "/cc/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/email"
  to = "/email/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/info"
  to = "/info/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/life"
  to = "/life/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/me"
  to = "/me/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/biz"
  to = "/biz/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/world"
  to = "/world/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/vip"
  to = "/vip/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/services"
  to = "/services/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/agency"
  to = "/agency/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/shop"
  to = "/shop/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/store"
  to = "/store/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/online"
  to = "/online/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/pro"
  to = "/pro/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/club"
  to = "/club/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/art"
  to = "/art/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[[redirects]]
  from = "/xyz"
  to = "/xyz/index.html"
  status = 200
  conditions = {Host = ["btcsaw.com", "www.btcsaw.com"]}

[build.environment]
  NODE_VERSION = "18"
